# Generated by Django 4.1 on 2022-10-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_cart_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
